// Code generated by protoc-gen-go. DO NOT EDIT.
// source: person.proto

// 包名，通过protoc生成go文件

package address

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 性别类型
// 枚举类型第一个字段必须为0
type GenderType int32

const (
	GenderType_SECRET GenderType = 0
	GenderType_FEMALE GenderType = 1
	GenderType_MALE   GenderType = 2
)

var GenderType_name = map[int32]string{
	0: "SECRET",
	1: "FEMALE",
	2: "MALE",
}

var GenderType_value = map[string]int32{
	"SECRET": 0,
	"FEMALE": 1,
	"MALE":   2,
}

func (x GenderType) String() string {
	return proto.EnumName(GenderType_name, int32(x))
}

func (GenderType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{0}
}

// 人
type Person struct {
	Id                   int64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Gender               GenderType `protobuf:"varint,3,opt,name=gender,proto3,enum=address.GenderType" json:"gender,omitempty"`
	Number               string     `protobuf:"bytes,4,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{0}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetGender() GenderType {
	if m != nil {
		return m.Gender
	}
	return GenderType_SECRET
}

func (m *Person) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

// 联系簿
type ContactBook struct {
	Persons              []*Person `protobuf:"bytes,1,rep,name=persons,proto3" json:"persons,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ContactBook) Reset()         { *m = ContactBook{} }
func (m *ContactBook) String() string { return proto.CompactTextString(m) }
func (*ContactBook) ProtoMessage()    {}
func (*ContactBook) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{1}
}

func (m *ContactBook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactBook.Unmarshal(m, b)
}
func (m *ContactBook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactBook.Marshal(b, m, deterministic)
}
func (m *ContactBook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactBook.Merge(m, src)
}
func (m *ContactBook) XXX_Size() int {
	return xxx_messageInfo_ContactBook.Size(m)
}
func (m *ContactBook) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactBook.DiscardUnknown(m)
}

var xxx_messageInfo_ContactBook proto.InternalMessageInfo

func (m *ContactBook) GetPersons() []*Person {
	if m != nil {
		return m.Persons
	}
	return nil
}

func init() {
	proto.RegisterEnum("address.GenderType", GenderType_name, GenderType_value)
	proto.RegisterType((*Person)(nil), "address.Person")
	proto.RegisterType((*ContactBook)(nil), "address.ContactBook")
}

func init() { proto.RegisterFile("person.proto", fileDescriptor_4c9e10cf24b1156d) }

var fileDescriptor_4c9e10cf24b1156d = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x4d, 0x5a, 0xb2, 0x3a, 0x2b, 0xeb, 0x32, 0x82, 0xe4, 0x18, 0x7a, 0x8a, 0x0a, 0x39,
	0xd4, 0x8b, 0x57, 0x2d, 0xd1, 0x8b, 0x82, 0xc4, 0xbe, 0x40, 0x6b, 0x82, 0x14, 0x69, 0x52, 0x93,
	0x7a, 0xf0, 0xed, 0xc5, 0xb4, 0xba, 0xb7, 0x2f, 0xf9, 0x87, 0x6f, 0xfe, 0x81, 0xd3, 0xc9, 0xc5,
	0x14, 0xbc, 0x9a, 0x62, 0x98, 0x03, 0x6e, 0x3a, 0x6b, 0xa3, 0x4b, 0xa9, 0xfa, 0x04, 0xf6, 0x92,
	0x03, 0xdc, 0x01, 0x1d, 0x2c, 0x27, 0x82, 0xc8, 0xc2, 0xd0, 0xc1, 0x22, 0x42, 0xe9, 0xbb, 0xd1,
	0x71, 0x2a, 0x88, 0x3c, 0x31, 0x99, 0xf1, 0x1a, 0xd8, 0xbb, 0xf3, 0xd6, 0x45, 0x5e, 0x08, 0x22,
	0x77, 0xf5, 0xb9, 0x5a, 0x3d, 0xea, 0x31, 0x7f, 0xb7, 0xdf, 0x93, 0x33, 0xeb, 0x08, 0x5e, 0x00,
	0xf3, 0x5f, 0x63, 0xef, 0x22, 0x2f, 0xb3, 0x62, 0x7d, 0x55, 0xb7, 0xb0, 0x6d, 0x82, 0x9f, 0xbb,
	0xb7, 0xf9, 0x3e, 0x84, 0x0f, 0xbc, 0x84, 0xcd, 0x52, 0x2d, 0x71, 0x22, 0x0a, 0xb9, 0xad, 0xcf,
	0xfe, 0xa5, 0x4b, 0x33, 0xf3, 0x97, 0x5f, 0x29, 0x80, 0xc3, 0x1e, 0x04, 0x60, 0xaf, 0xba, 0x31,
	0xba, 0xdd, 0x1f, 0xfd, 0xf2, 0x83, 0x7e, 0xbe, 0x7b, 0xd2, 0x7b, 0x82, 0xc7, 0x50, 0x66, 0xa2,
	0x3d, 0xcb, 0xc7, 0xde, 0xfc, 0x04, 0x00, 0x00, 0xff, 0xff, 0x14, 0x09, 0x0f, 0x7e, 0xfc, 0x00,
	0x00, 0x00,
}
